"""将已验收的 Teacher train rollout 转成 conversational SFT JSONL。"""

import argparse
import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .environment_reward import STATE_CHANGING_TOOLS
from .tasks.spec import TaskSpec


@dataclass(frozen=True)
class SFTBuildStats:
    total_records: int
    accepted_records: int
    skipped_not_accepted: int
    train_rows: int
    validation_rows: int


def load_task_specs(path: Path) -> dict[str, TaskSpec]:
    tasks = [
        TaskSpec.model_validate_json(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    if any(task.split != "train" for task in tasks):
        raise ValueError(f"SFT 数据只能使用 train 任务：{path}")
    return {task.task_id: task for task in tasks}


def _validated_messages(record: dict[str, Any], source: Path) -> list[dict[str, str]]:
    rollout = record.get("rollout")
    if not isinstance(rollout, dict):
        raise ValueError(f"{source}: 缺少 rollout")
    if rollout.get("termination_reason") != "finished":
        raise ValueError(f"{source}: sft_accepted 轨迹必须正常 finish")
    messages = rollout.get("messages")
    if not isinstance(messages, list) or not messages:
        raise ValueError(f"{source}: 缺少完整 messages，不能构造 SFT 样本")

    normalized: list[dict[str, str]] = []
    for index, message in enumerate(messages):
        if not isinstance(message, dict):
            raise ValueError(f"{source}: messages[{index}] 不是对象")
        role = message.get("role")
        content = message.get("content")
        if role not in {"system", "user", "assistant"} or not isinstance(content, str):
            raise ValueError(f"{source}: messages[{index}] 不是标准 chat message")
        normalized.append({"role": role, "content": content})
    if not any(message["role"] == "assistant" for message in normalized):
        raise ValueError(f"{source}: 没有可学习的 assistant 输出")
    return normalized


def _has_clean_sft_process(rollout: dict[str, Any]) -> bool:
    """Defend against stale evaluator flags in records generated by older processes."""

    steps = rollout.get("steps", [])
    if not isinstance(steps, list):
        return False
    state_version = 0
    seen_tool_calls: set[tuple[int, str]] = set()
    for step in steps:
        if not isinstance(step, dict) or step.get("parse_error") is not None:
            return False
        action = step.get("action")
        if action is None:
            continue
        if not isinstance(action, dict):
            return False
        if action.get("action_type") == "tool":
            observation = step.get("observation")
            if not isinstance(observation, dict) or observation.get("success") is not True:
                return False
            call_signature = json.dumps(
                {"tool_name": action.get("tool_name"), "arguments": action.get("arguments")},
                ensure_ascii=True,
                sort_keys=True,
            )
            call_key = (state_version, call_signature)
            if call_key in seen_tool_calls:
                return False
            seen_tool_calls.add(call_key)
            if action.get("tool_name") in STATE_CHANGING_TOOLS:
                state_version += 1
    return True


def collect_sft_rows(records_dir: Path, tasks_path: Path) -> tuple[list[dict[str, Any]], int, int]:
    """只接受 train split 中由主 Evaluator 标记为 sft_accepted 的轨迹。"""

    tasks = load_task_specs(tasks_path)
    rows: list[dict[str, Any]] = []
    total_records = 0
    skipped_not_accepted = 0
    for source in sorted(records_dir.glob("*.json")):
        if source.name == "summary.json":
            continue
        total_records += 1
        try:
            record = json.loads(source.read_text(encoding="utf-8"))
        except json.JSONDecodeError as error:
            raise ValueError(f"{source}: 不是合法 JSON") from error
        if not isinstance(record, dict):
            raise ValueError(f"{source}: 顶层必须是对象")

        rollout = record.get("rollout")
        evaluation = record.get("evaluation")
        if not isinstance(rollout, dict) or not isinstance(evaluation, dict):
            raise ValueError(f"{source}: 缺少 rollout 或 evaluation")
        task_id = rollout.get("task_id")
        task = tasks.get(task_id)
        if task is None:
            raise ValueError(f"{source}: task_id={task_id!r} 不在指定 train 任务集")
        if task.status != "supported":
            raise ValueError(f"{source}: 不支持的任务不能进入 SFT")
        if not evaluation.get("sft_accepted", False) or not _has_clean_sft_process(rollout):
            skipped_not_accepted += 1
            continue

        rows.append(
            {
                "task_id": task.task_id,
                "source_record": source.name,
                "messages": _validated_messages(record, source),
            }
        )
    return rows, total_records, skipped_not_accepted


def split_rows_by_task(
    rows: list[dict[str, Any]],
    validation_ratio: float,
    seed: int,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """稳定地按 task_id 划分，避免同题不同轨迹同时出现在训练和验证中。"""

    if not 0.0 <= validation_ratio < 1.0:
        raise ValueError("validation_ratio 必须在 [0, 1) 内")
    task_ids = sorted({row["task_id"] for row in rows})
    if validation_ratio == 0 or len(task_ids) < 2:
        return list(rows), []
    ordered_ids = sorted(
        task_ids,
        key=lambda task_id: hashlib.sha256(f"{seed}:{task_id}".encode()).hexdigest(),
    )
    validation_count = min(
        len(ordered_ids) - 1,
        max(1, round(len(ordered_ids) * validation_ratio)),
    )
    validation_ids = set(ordered_ids[:validation_count])
    return (
        [row for row in rows if row["task_id"] not in validation_ids],
        [row for row in rows if row["task_id"] in validation_ids],
    )


def _write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = "".join(json.dumps(row, ensure_ascii=False) + "\n" for row in rows)
    path.write_text(payload, encoding="utf-8")


def build_sft_dataset(
    *,
    records_dir: Path,
    tasks_path: Path,
    output_dir: Path,
    validation_ratio: float = 0.12,
    seed: int = 42,
) -> SFTBuildStats:
    rows, total_records, skipped_not_accepted = collect_sft_rows(records_dir, tasks_path)
    if not rows:
        raise ValueError("没有 evaluation.sft_accepted=true 的 Teacher train 轨迹")
    train_rows, validation_rows = split_rows_by_task(rows, validation_ratio, seed)
    _write_jsonl(output_dir / "train.jsonl", train_rows)
    _write_jsonl(output_dir / "validation.jsonl", validation_rows)
    manifest = {
        "records_dir": str(records_dir.resolve()),
        "tasks_path": str(tasks_path.resolve()),
        "total_records": total_records,
        "accepted_records": len(rows),
        "skipped_not_accepted": skipped_not_accepted,
        "train_rows": len(train_rows),
        "validation_rows": len(validation_rows),
        "validation_ratio": validation_ratio,
        "seed": seed,
        "split_unit": "task_id",
    }
    (output_dir / "manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return SFTBuildStats(
        total_records=total_records,
        accepted_records=len(rows),
        skipped_not_accepted=skipped_not_accepted,
        train_rows=len(train_rows),
        validation_rows=len(validation_rows),
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--records-dir", type=Path, required=True)
    parser.add_argument("--tasks", type=Path, default=Path("data/tasks/train.jsonl"))
    parser.add_argument("--output-dir", type=Path, default=Path("data/sft"))
    parser.add_argument("--validation-ratio", type=float, default=0.12)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    stats = build_sft_dataset(
        records_dir=args.records_dir,
        tasks_path=args.tasks,
        output_dir=args.output_dir,
        validation_ratio=args.validation_ratio,
        seed=args.seed,
    )
    print(json.dumps(stats.__dict__, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
